name: velib_data_ingestion_dbt
version: "1.0"
config-version: 2

profile: velib_data_ingestion_dbt

model-paths: ["models"]
macro-paths: ["macros"]

models:
  velib_data_ingestion_dbt:
    marts:
      +materialized: incremental
